version: '3'

services:
  app:
    image: rentalsimage:latest
    ports:
      - "8080:8080"
    depends_on:
      - db

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/rentals
      SPRING_DATASOURCE_USERNAME: bruno
      SPRING_DATASOURCE_PASSWORD: toledo
    networks:
      - "mired"

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: rentals
      POSTGRES_USER: bruno
      POSTGRES_PASSWORD: toledo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/docker/volumes/rentalsdata/_data
    networks:
      - "mired"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - "mired"

networks:
  mired:
    driver: bridge

volumes:
  postgres_data:
